#Use this dockerfile if you have an existing gatsby site
#and just want an environment to run gatsby development
#copy this and the compose file innto the root fo your gatsby
#directory, then docker-compose up

FROM node:alpine

# Also exposing VSCode debug ports
EXPOSE 8000 9000 9929 9230

RUN apk add --no-cache python make g++ git \
 && apk add vips-dev fftw-dev build-base \
        --update-cache \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/community \
        --repository https://alpine.global.ssl.fastly.net/alpine/edge/main \
 && rm -fR /var/cache/apk/*

RUN npm install -g gatsby-cli

WORKDIR /app
COPY ./package.json .
RUN yarn install && yarn cache clean
COPY . .
CMD ["yarn", "develop", "-H", "0.0.0.0" ]